# Generated by Django 2.1.4 on 2018-12-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('author_rating', models.IntegerField(blank=True)),
                ('about_author', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Unpublished', max_length=25)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('currency', models.CharField(default='Ruppes', max_length=20)),
                ('publish_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genredetails', models.TextField()),
                ('slug', models.CharField(max_length=20)),
                ('MetaData', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=20)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='sub_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.SubGenre'),
        ),
    ]
